### PR TITLE
rollup of several outstanding PRs + bump MSRV to Rust 1.73

### PR DESCRIPTION
**Pull request by BurntSushi**
This is a rollup of a few outstanding PRs.

I'll do a minor version bump, so I'll take advantage of that opportunity and bump the MSRV to Rust 1.73.

Closes #160, Closes #189, Closes #191, Closes #192, Closes #197

### CODE REVIEW

**Comment by BurntSushi** [comment]
This PR is on crates.io in `bstr 1.11.0`.

**Comment by lopopolo** [comment]
@BurntSushi https://github.com/BurntSushi/bstr/pull/189 I think is a breaking change. The change in casing of `BStr`'s debug format ended up breaking some tests of mine.

Given one of the documented uses of `BStr` is to provide human readable debug output, I thought that meant the debug format would be stable (modulo bug fixes). Curious what you think here.

**Comment by BurntSushi** [comment]
I think it's a pretty strong convention that the output of `Debug` impls isn't meant to be stable. We've never considered it as such in std anyway. I don't know if that policy is written down anywhere though. But I think it's just generally impractical to consider `Debug` output to be stable. Consider that `derive(Debug)` will by default leak the internal details of a type. So if you add or remove or change an internal field of a type, that in turn will change the `Debug` output on a `derive(Debug)` for example.

I do agree that the `Debug` impl for `BStr` is one of the stars of the show here, but there really isn't any explicit guarantee of what it will be emitted. The only documented guarantee is that invalid bytes are emitted as hex escapes.

And the fix here is making the output more consistent. I certainly meant for the case of the hex escapes to all be the same. But it wasn't.

**Comment by lopopolo** [comment]
cool, thanks for the detailed explanation! I'll update my tests 🫡

**Pull request merged**
